DROP TABLE IF EXISTS `cv2`.`affiliatecpmdata`;
CREATE TABLE `cv2`.`affiliatecpmdata` (
  `id` int(11) NOT NULL auto_increment,
  `advertiseAffiliateId` int(11) default NULL,
  `semId` int(11) unsigned default NULL,
  `advertiseId` int(11) unsigned default NULL,
  `trackCode` varchar(50) default NULL,
  `campaignId` int(11) default NULL,
  `affiliateId` int(11) default NULL,
  `siteId` int(11) default NULL,
  `subSiteId` varchar(255) default NULL,
  `dispalyType` int(1) default '0',
  `dataType` int(1) default '0',
  `dataTotal` bigint(20) default '0',
  `ruleType` int(4) unsigned default NULL,
  `trackStatus` int(1) default '0',
  `trackStep` int(2) default '0',
  `orderid` varchar(1024) default NULL,
  `orderamount` float(14,2) default '0.00',
  `orderinfo` varchar(4096) default NULL,
  `trackIp` varchar(255) default NULL,
  `trackUser` varchar(50) default NULL,
  `referrerUrl` varchar(2048) default NULL,
  `trackTime` datetime default NULL,
  `createdAt` datetime default NULL,
  `updatedAt` datetime default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `cpm_trackDataUniqueIndex` (`advertiseAffiliateId`,`ruleType`,`trackStep`,`trackIp`,`trackTime`),
  KEY `cpm_indexTrackDataOnTrackStep` (`trackStep`),
  KEY `cpm_indexTrackDataOnTrackTime` (`trackTime`),
  KEY `cpm_indexTrackDataOnTrackIp` (`trackIp`),
  KEY `cpm_indexTrackDataOnTrackStatus` (`trackStatus`),
  KEY `cpm_indexTrackDataOnCampaignId` (`campaignId`),
  KEY `cpm_indexTrackDataOnAffiliateId` (`affiliateId`),
  KEY `cpm_indexTrackDataOnTrackUser` (`trackUser`),
  KEY `cpm_indexTrackDataonTrackCode` (`trackCode`),
  KEY `cpm_indexOfSemId` (`semId`),
  KEY `cpm_indexOfAdvertiseId` (`advertiseId`),
  KEY `cpm_indexTrackDataOnTrackType` (`ruleType`)
) ENGINE=MyISAM CHARSET=utf8;