DROP TABLE IF EXISTS `cv2`.`report_trackmatch`;
CREATE TABLE  `cv2`.`report_trackmatch` (
  `id` int(11) NOT NULL,
  `advertiserId` int(11) unsigned default NULL,
  `campaignId` int(11) default NULL,
  `affiliateId` int(11) default NULL,
  `siteId` int(11) default NULL,
  `subSiteId` varchar(255) default NULL,
  `advertiseAffiliateId` int(11) default NULL,

  `semId` int(11) unsigned default NULL,
  `trackCode` varchar(50) default NULL,
  `dispalyType` int(1) default '0',
  `dataType` int(1) default '0',
  `dataTotal` bigint(20) default '0',
  `ruleType` int(4) unsigned default NULL,
  `trackStatus` int(1) default '0',
  `trackStep` int(2) default '0',
  `orderid` varchar(50) default '',
  `orderamount` float(14,2) default 0,
  `orderinfo` varchar(1024) default NULL,
  `trackIp` varchar(255) default NULL,
  `trackUser` varchar(50) default NULL,
  `referrerUrl` varchar(2048) default NULL,
  `trackTime` datetime default NULL,
  `siteCommisionOld` float(12,3) default 0,
  `siteCommisionNew` float(12,3) default 0,
  `darwCommisionOld` float(12,3) default 0,
  `darwCommisionNew` float(12,3) default 0,
  `matched` smallint(1) default 0,
  `matchId` varchar(30) default '',
  `createdAt` datetime default NULL,
  `updatedAt` datetime default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `rpt_thuid` (`advertiseAffiliateId`,`ruleType`,`trackStep`,`trackIp`,`trackTime`),
  KEY `rpt_thTrackStep` (`trackStep`),
  KEY `rpt_thTrackTime` (`trackTime`),
  KEY `rpt_thTrackIp` (`trackIp`),
  KEY `rpt_thTrackStatus` (`trackStatus`),
  KEY `rpt_thCampaignId` (`campaignId`),
  KEY `rpt_thAffiliateId` (`affiliateId`),
  KEY `rpt_thTrackUser` (`trackUser`),
  KEY `rpt_thTrackCode` (`trackCode`),
  KEY `rpt_thSemId` (`semId`),
  KEY `rpt_thAdvertiseId` (`advertiserId`),
  KEY `rpt_thTrackType` (`ruleType`),
  KEY `rpt_thMatchId` (`matchId`),
  KEY `rpt_thMatched` (`matched`),
  KEY `rpt_thAdvertiseAffiliateId` (`advertiseAffiliateId`),
  KEY `rpt_thSubSiteId` (`subSiteId`)
) ENGINE=InnoDB CHARSET=utf8;


