DROP TABLE IF EXISTS `cv2`.`report_trackdata`;
CREATE TABLE  `cv2`.`report_trackdata` (
  `id` int(11) NOT NULL,
  `advertiseAffiliateId` int(11) default NULL,
  `semId` int(11) unsigned default NULL,
  `advertiseId` int(11) unsigned default NULL,
  `trackCode` varchar(50) default NULL,
  `campaignId` int(11) default NULL,
  `affiliateId` int(11) default NULL,
  `siteId` int(11) default NULL,
  `subSiteId` varchar(255) default NULL,
  `dispalyType` int(1) default '0',
  `dataType` int(1) default '0',
  `dataTotal` bigint(20) default '0',
  `ruleType` int(4) unsigned default NULL,
  `trackStatus` int(1) default '0',
  `trackStep` int(2) default '0',
  `orderid` varchar(50) default '',
  `orderamount` float(14,2) default 0,
  `orderinfo` varchar(1024) default NULL,
  `trackIp` varchar(255) default NULL,
  `trackUser` varchar(50) default NULL,
  `referrerUrl` varchar(2048) default NULL,
  `trackTime` datetime default NULL,
  `createdAt` datetime default NULL,
  `updatedAt` datetime default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `rpt_tduid` (`advertiseAffiliateId`,`ruleType`,`trackStep`,`trackIp`,`trackTime`),
  KEY `rpt_tdTrackStep` (`trackStep`),
  KEY `rpt_tdTrackTime` (`trackTime`),
  KEY `rpt_tdTrackIp` (`trackIp`),
  KEY `rpt_tdTrackStatus` (`trackStatus`),
  KEY `rpt_tdCampaignId` (`campaignId`),
  KEY `rpt_tdAffiliateId` (`affiliateId`),
  KEY `rpt_tdTrackUser` (`trackUser`),
  KEY `rpt_tdTrackCode` (`trackCode`),
  KEY `rpt_tdSemId` (`semId`),
  KEY `rpt_tdAdvertiseId` (`advertiseId`),
  KEY `rpt_tdTrackType` (`ruleType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


