DROP TABLE IF EXISTS `cv2`.`summarycommission`;
CREATE TABLE `cv2`.`summarycommission` (
  `id` int(11) NOT NULL auto_increment,

  `advertiserId` int(11) default 0,
  `advertiserName` varchar(255) default NULL,
  `campaignId` int(11) default 0,
  `campaignName` varchar(255) default NULL,
  `affiliateId` int(11) default 0,
  `affiliateName` varchar(255) default NULL,
  `siteId` int(4) default 0,
  `siteName` varchar(255) default NULL,
  `siteUrl` varchar(255) default NULL,
  `subSiteId` varchar(255) default '',

  `advertiseAffiliateId` int(11) default 0,
  `bannerId` int(11) default 0,
  `bannerDescription` varchar(255) default NULL,
  `landingPageId` int(11) default 0,
  `landingPageUrl` varchar(1024) default NULL,

  `summaryDate` date NOT NULL,
  `ruleType` int(4) NOT NULL default '0',
  `dataTotalOld` int(11) NOT NULL default '0',
  `dataTotalNew` int(11) default '0',
  `orderamountOld` float(11,3) unsigned default '0.000',
  `orderamountNew` float(11,3) unsigned default '0.000',
  `siteCommisionOld` float(11,3) unsigned default '0.000',
  `siteCommisionNew` float(11,3) unsigned default '0.000',
  `darwCommisionOld` float(11,3) unsigned default '0.000',
  `darwCommisionNew` float(11,3) unsigned default '0.000',

  `balanceId` varchar(32) default 0,
  `balanced` int(1) default '0',
  `balanceDate` date default NULL,
  `createdAt` datetime default NULL,
  `updatedAt` datetime default NULL,

  PRIMARY KEY  (`id`),
  UNIQUE KEY `sc_indexSummaryOnAdvertiseAffiliateIdAndSummaryDate` (`advertiseAffiliateId`,`subSiteId`,`summaryDate`,`ruleType`),
  KEY `sc_indexSummaryOnSummaryDate` (`summaryDate`),
  KEY `sc_indexSummaryOnbalanced` (`balanced`),
  KEY `sc_indexSummaryOnbalanceDate` (`balanceDate`),
  KEY `sc_indexOfadvertiserId` (`advertiserId`),
  KEY `sc_indexOfcampaignId` (`campaignId`),
  KEY `sc_indexOfaffiliateId` (`affiliateId`),
  KEY `sc_indexOfsiteId` (`siteId`),
  KEY `sc_indexOfsubSiteId` (`subSiteId`),
  KEY `sc_indexOfadvertiseAffiliateId` (`advertiseAffiliateId`),
  KEY `sc_indexOfbannerId` (`bannerId`),
  KEY `sc_indexOfbalanceId` (`landingPageId`),
  KEY `sc_indexOflandingPageId` (`balanceId`),
  KEY `sc_indexOfbalanceDate` (`balanceDate`)
) ENGINE=InnoDB CHARSET=utf8;