package cn.clickvalue.cv2.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import org.hibernate.annotations.GenericGenerator;

/**
 * Effectreport generated by MyEclipse Persistence Tools
 */
@Entity
public class EffectReport implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(generator = "c-assigned")
	@GenericGenerator(name = "c-assigned", strategy = "assigned")
	private String id;

	private String verified;

	private String cpc;

	private String confirmedCpc;

	private String cpcMoney;

	private String confirmedCpcMoney;

	private String cpl;

	private String confirmedCpl;

	private String cplMoney;

	private String confirmedCplMoney;

	private String cps;

	private String confirmedCps;

	private String cpsMoney;

	private String confirmedCpsMoney;

	private String moneycount;

	private String confirmedMoneycount;

	private String confirmRate;

	private String campaingId;

	private String campaingName;

	private String cpm;

	private String confirmedCpm;

	private String cpmMoney;

	private String confirmedCpmMoney;

	private String affiliateId;

	private String affiliateName;

	private String advertiserId;

	private String advertiserName;

	private String affiliateSiteId;

	private String affiliateSiteName;

	private String advertiserSiteId;

	private String advertiserSiteName;

	// Constructors

	public EffectReport(String id, Date createTime, String verified, String cpc, String confirmedCpc, String cpcMoney,
			String confirmedCpcMoney, String cpl, String confirmedCpl, String cplMoney, String confirmedCplMoney,
			String cps, String confirmedCps, String cpsMoney, String confirmedCpsMoney, String moneycount,
			String confirmedMoneycount, String confirmRate, String campaingId, String campaingName, String cpm,
			String confirmedCpm, String cpmMoney, String confirmedCpmMoney, String affiliateId, String affiliateName,
			String advertiserId, String advertiserName, String affiliateSiteId, String affiliateSiteName,
			String advertiserSiteId, String advertiserSiteName) {
		super();
		this.id = id;
		this.verified = verified;
		this.cpc = cpc;
		this.confirmedCpc = confirmedCpc;
		this.cpcMoney = cpcMoney;
		this.confirmedCpcMoney = confirmedCpcMoney;
		this.cpl = cpl;
		this.confirmedCpl = confirmedCpl;
		this.cplMoney = cplMoney;
		this.confirmedCplMoney = confirmedCplMoney;
		this.cps = cps;
		this.confirmedCps = confirmedCps;
		this.cpsMoney = cpsMoney;
		this.confirmedCpsMoney = confirmedCpsMoney;
		this.moneycount = moneycount;
		this.confirmedMoneycount = confirmedMoneycount;
		this.confirmRate = confirmRate;
		this.campaingId = campaingId;
		this.campaingName = campaingName;
		this.cpm = cpm;
		this.confirmedCpm = confirmedCpm;
		this.cpmMoney = cpmMoney;
		this.confirmedCpmMoney = confirmedCpmMoney;
		this.affiliateId = affiliateId;
		this.affiliateName = affiliateName;
		this.advertiserId = advertiserId;
		this.advertiserName = advertiserName;
		this.affiliateSiteId = affiliateSiteId;
		this.affiliateSiteName = affiliateSiteName;
		this.advertiserSiteId = advertiserSiteId;
		this.advertiserSiteName = advertiserSiteName;
	}

	/** default constructor */
	public EffectReport() {
	}

	/** minimal constructor */
	public EffectReport(String id) {
		this.id = id;
	}

	/** full constructor */

	// Property accessors
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getVerified() {
		return this.verified;
	}

	public void setVerified(String verified) {
		this.verified = verified;
	}

	public String getCpc() {
		return this.cpc;
	}

	public void setCpc(String cpc) {
		this.cpc = cpc;
	}

	public String getConfirmedCpc() {
		return this.confirmedCpc;
	}

	public void setConfirmedCpc(String confirmedCpc) {
		this.confirmedCpc = confirmedCpc;
	}

	public String getCpcMoney() {
		return this.cpcMoney;
	}

	public void setCpcMoney(String cpcMoney) {
		this.cpcMoney = cpcMoney;
	}

	public String getConfirmedCpcMoney() {
		return this.confirmedCpcMoney;
	}

	public void setConfirmedCpcMoney(String confirmedCpcMoney) {
		this.confirmedCpcMoney = confirmedCpcMoney;
	}

	public String getCpl() {
		return this.cpl;
	}

	public void setCpl(String cpl) {
		this.cpl = cpl;
	}

	public String getConfirmedCpl() {
		return this.confirmedCpl;
	}

	public void setConfirmedCpl(String confirmedCpl) {
		this.confirmedCpl = confirmedCpl;
	}

	public String getCplMoney() {
		return this.cplMoney;
	}

	public void setCplMoney(String cplMoney) {
		this.cplMoney = cplMoney;
	}

	public String getConfirmedCplMoney() {
		return this.confirmedCplMoney;
	}

	public void setConfirmedCplMoney(String confirmedCplMoney) {
		this.confirmedCplMoney = confirmedCplMoney;
	}

	public String getCps() {
		return this.cps;
	}

	public void setCps(String cps) {
		this.cps = cps;
	}

	public String getConfirmedCps() {
		return this.confirmedCps;
	}

	public void setConfirmedCps(String confirmedCps) {
		this.confirmedCps = confirmedCps;
	}

	public String getCpsMoney() {
		return this.cpsMoney;
	}

	public void setCpsMoney(String cpsMoney) {
		this.cpsMoney = cpsMoney;
	}

	public String getConfirmedCpsMoney() {
		return this.confirmedCpsMoney;
	}

	public void setConfirmedCpsMoney(String confirmedCpsMoney) {
		this.confirmedCpsMoney = confirmedCpsMoney;
	}

	public String getMoneycount() {
		return this.moneycount;
	}

	public void setMoneycount(String moneycount) {
		this.moneycount = moneycount;
	}

	public String getConfirmRate() {
		return this.confirmRate;
	}

	public void setConfirmRate(String confirmRate) {
		this.confirmRate = confirmRate;
	}

	public String getCampaingId() {
		return this.campaingId;
	}

	public void setCampaingId(String campaingId) {
		this.campaingId = campaingId;
	}

	public String getCampaingName() {
		return this.campaingName;
	}

	public void setCampaingName(String campaingName) {
		this.campaingName = campaingName;
	}

	public String getCpm() {
		return this.cpm;
	}

	public void setCpm(String cpm) {
		this.cpm = cpm;
	}

	public String getConfirmedCpm() {
		return this.confirmedCpm;
	}

	public void setConfirmedCpm(String confirmedCpm) {
		this.confirmedCpm = confirmedCpm;
	}

	public String getCpmMoney() {
		return this.cpmMoney;
	}

	public void setCpmMoney(String cpmMoney) {
		this.cpmMoney = cpmMoney;
	}

	public String getConfirmedCpmMoney() {
		return this.confirmedCpmMoney;
	}

	public void setConfirmedCpmMoney(String confirmedCpmMoney) {
		this.confirmedCpmMoney = confirmedCpmMoney;
	}

	public String getAffiliateId() {
		return this.affiliateId;
	}

	public void setAffiliateId(String affiliateId) {
		this.affiliateId = affiliateId;
	}

	public String getAffiliateName() {
		return this.affiliateName;
	}

	public void setAffiliateName(String affiliateName) {
		this.affiliateName = affiliateName;
	}

	public String getAdvertiserId() {
		return this.advertiserId;
	}

	public void setAdvertiserId(String advertiserId) {
		this.advertiserId = advertiserId;
	}

	public String getAdvertiserName() {
		return this.advertiserName;
	}

	public void setAdvertiserName(String advertiserName) {
		this.advertiserName = advertiserName;
	}

	public String getAffiliateSiteId() {
		return this.affiliateSiteId;
	}

	public void setAffiliateSiteId(String affiliateSiteId) {
		this.affiliateSiteId = affiliateSiteId;
	}

	public String getAffiliateSiteName() {
		return this.affiliateSiteName;
	}

	public void setAffiliateSiteName(String affiliateSiteName) {
		this.affiliateSiteName = affiliateSiteName;
	}

	public String getAdvertiserSiteId() {
		return this.advertiserSiteId;
	}

	public void setAdvertiserSiteId(String advertiserSiteId) {
		this.advertiserSiteId = advertiserSiteId;
	}

	public String getAdvertiserSiteName() {
		return this.advertiserSiteName;
	}

	public void setAdvertiserSiteName(String advertiserSiteName) {
		this.advertiserSiteName = advertiserSiteName;
	}

	public String getConfirmedMoneycount() {
		return confirmedMoneycount;
	}

	public void setConfirmedMoneycount(String confirmedMoneycount) {
		this.confirmedMoneycount = confirmedMoneycount;
	}

}