package cn.clickvalue.cv2.model;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import cn.clickvalue.cv2.model.base.PersistentObject;

/**
 * Operation generated by MyEclipse Persistence Tools
 */
@Entity
public class Operation extends PersistentObject {

	private static final long serialVersionUID = 1L;

	private String name;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "operationTypeId")
	private OperationType operationType;

	private String link;

	public Operation() {
	}

	// Property accessors
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public OperationType getOperationType() {
		return operationType;
	}

	public void setOperationType(OperationType operationType) {
		this.operationType = operationType;
	}
}