package cn.clickvalue.cv2.common.Enum;

public enum HPBlockEnum {
	LATEST_CAMPAIGN, RECOMMEND_CAMPAIGNS, BANNER, SEO, WEBSITE_DESIGN, EXCHANGE, HOT_PLACARD, HOME_LINKS, INNER_LINKS, INNER_BANNER_LINKS;
}
